"""add show_card_title to decks

Revision ID: 20250220_show_card_title
Revises: 20250201_media_arrays
Create Date: 2026-02-20 13:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20250220_show_card_title"
down_revision: Union[str, None] = "20250201_media_arrays"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decks", sa.Column("show_card_title", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("decks", "show_card_title")
    # ### end Alembic commands ###
